import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import { Nav } from '~/app/components/layout/nav';
import { Footer } from '~/app/components/layout/footer';
import { Toaster } from '~/components/ui/toaster';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <div className="flex justify-center items-center">
          <Nav />
        </div>
        {/* // NOTE: possibly remove min-h-screen */}
        <div className="min-h-screen overflow-x-hidden">{children}</div>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
